version: "3"
services:
  webserver:
    build: "."
    container_name: goodvotes-web
    ports:
      - "127.0.0.1:$GOODVOTES_PORT:5000"
    volumes:
      - "storage":/App/storage
    env_file:
      - .env
