version: "3"
services:
  webserver:
    image: goodvotex
    build:
      dockerfile: docker/Dockerfile
      context: .
    container_name: goodvotex-webservice
    ports:
        - "$GOODVOTEX_HOST:$GOODVOTEX_PORT:80"
    volumes:
        - ./storage:/App/storage
        - ./goodvotex:/App/goodvotex
    env_file: .env
    entrypoint: sh -c 'flask goodvotex create-db; flask auth add-user admin "Armin Admin" "${GOODVOTEX_ADMIN_EMAIL}" "${GOODVOTEX_AMIN_PASSWORD}"; flask run --host=0.0.0.0 --port=80 --debug;'

